/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mylib;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.context.Initialized;
import javax.enterprise.event.Observes;
import javax.servlet.ServletContext;

@ApplicationScoped
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public void init(@Observes @Initialized(ApplicationScoped.class) Object init) {
        System.out.println(" ### log-1 mylib.Library.init(java.lang.Object) called ###");
    }

    public void init(@Observes @Initialized(ApplicationScoped.class) ServletContext init) {
        System.out.println(" ### log-2 mylib.Library.init(javax.servlet.ServletContext) invoked ###");
    }
}
